# docker compose run --service-ports --rm node

services:
  arora-web-dev:
    image: ghcr.io/armando-fandango/ezdev/ezdev:0.4-base-bullseye-slim
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ${PWD}:/arora-web
    ports:
      - "3000"
    working_dir: /arora-web
    #build: 
    #  context: .
    #  dockerfile: dockerfiles/Dockerfile-node