FROM node:20-bullseye-slim

RUN apt-get -q update \
    && apt-get -q purge -y snapd \
    && apt-get -qq install -y --no-install-recommends \
      software-properties-common \
      sudo \
      lsb-release \
      gnupg2 \
      ca-certificates \
      wget curl rsync \
      build-essential \
      autoconf automake libtool ninja-build pkg-config \
      git git-lfs \
      python-is-python3 python3-pip \
      mesa-utils \
      vulkan-tools \
      nano vim \
      terminator \
    && apt-get -q autoremove --purge && apt-get -q clean && rm -rf /var/lib/apt/lists/*

    SHELL ["/bin/bash", "-c"]
    CMD ["bash"]