name: 'deploy-pages'

on:
  push:
    branches: ['ts']
  #pull_request:
  #  branches: [ "ts" ]

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/armando-fandango/ez/ez:0.4-base-bullseye-slim
      options: --cpus 1 --user 1001
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: install dependencies
        run: npm ci --ignore-scripts
      - name: deploy to github pages
        # run: npm run deploy
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
